version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: unless-stopped
