name: Deploy Node.js App with Docker and Redis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose locally
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Deploy to the remote server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Deploying Docker Compose app on remote server..."
            cd /path/to/your/project || exit
            docker-compose down
            docker-compose up -d --build
            echo "Deployment successful!"
